### ISSUE TITLE
項目ごとにページをわけてはどうか？

### ISSUE THREAD

**Issue by mignonstyle** [wckansai2016/make-wp-theme#10]
去年の宮さんのハンズオン資料のように、項目ごとでわけたほうが見やすいかなと思いました。
https://github.com/wckansai2015/how-to-develop-wp-plugin

**Comment by kurudrive** [comment]
うーむ、これについては、今回やる内容が多くて人によって速度差が大きいと思うので、ページが遷移すると
「今どこやってるの？見てるページはあってる？」
という人が発生して、その人がどのページを見てるのか？今やってるのはどのページなのかを確認して、違うページを見てるようだったら
「◯◯のページに移動して〜...え〜っと、このリンクからこのページに移動して〜...」
みたいなやりとりをしないといけないけど、ページ遷移がなければそのページのまま
「今全体の真ん中くらいの◯◯のところ」
って言えるし、ソースや参考URLを画面に写したりする事も踏まえると、僕としてはハンズオンでは1頁完結の方が進行しやすいと思います。
ただ、やってる箇所は指示しやすいように、前日くらいに大見出しには通し番号を追加しようと思ってます。

**Comment by mignonstyle** [comment]
了解です！ありがとうございますー！
