### ISSUE TITLE
ヘッダーのタイトル／リンク／キャッチフレーズを設定 のところ

### ISSUE THREAD

**Issue by mignonstyle** [wckansai2016/make-wp-theme#5]
echo get_bloginfo() 使っているのがちょっと気になりました。せっかく出力用の bloginfo() があるので、わざわざ get_bloginfo() 使う必要性はないかなと思います。

**Comment by kurudrive** [comment]
変更しました :)

**Comment by mignonstyle** [comment]
確認しました。
修正ありがとうございますー
