### ISSUE TITLE
プラグインなど外部から操作出来るようになる

### ISSUE THREAD

**Issue by mignonstyle** [wckansai2016/make-wp-theme#6]
ここは初めての人には難しいし、時間的にもカットしてよいかと思います。

**Comment by kurudrive** [comment]
ハンズオン参加者の中で、
「 HTMLやCSSの知識の薄い人」もいれば「テーマ作ったことある人」いると思うので、そういう"ある程度の知識のある人"向けに少し難しい内容はあった方が
「全部知ってる内容で参加した意味がなかった」
という状態にならなくていいかなと思いつつ・・・
実際に説明してる時間はないと思うので、資料には記載しつつ現場での説明は省略しようと思います。

**Comment by mignonstyle** [comment]
> 資料には記載しつつ現場での説明は省略しようと思います。

はい。それでよいと思います。
よろしくお願いします。

**Comment by kurudrive** [comment]
おいっす
