### ISSUE TITLE
サイドバーの設定

### ISSUE THREAD

**Issue by mignonstyle** [wckansai2016/make-wp-theme#7]
カテゴリーリストと月別アーカイブリストはウィジェットがあるのでサイドバーの項目を変えるか、ウィジェットを使用したほうがよいのではないでしょうか。

**Comment by kurudrive** [comment]
https://github.com/wckansai2016/make-wp-theme/commit/350b70cc9ead4549b75f88be88892f2e61847d2c

**Comment by kurudrive** [comment]
ウィジェットの説明追加しました。
ただ、いきなりウィジェット説明するとちょっと理解しにくいかもしれないので、時間にもよりけりですが、カテゴリーリストや月別リストはイキにしたいです。
状況によって飛ばすかどうか判断しようかと。

**Comment by mignonstyle** [comment]
そうですねー。
参加者さんのペースにあわせて、難しそうだったらウィジェットは紹介だけ、慣れてる人が多いようだったらウィジェット作成までという感じでよいかと思いますー。
