### ISSUE TITLE
時間があれば

### ISSUE THREAD

**Issue by mignonstyle** [wckansai2016/make-wp-theme#8]
パンくずリストはプラグインもありますし、初心者対象の今回のハンズオンでは必要ないかと思いますがいかがでしょうか？
トップビジュアルとパンくずの表示切り替え（条件分岐）もなくてもいいような気がします。
パンくずよりウィジェットのほうがテーマ基礎っぽくて良いかなと思います。

パーツテンプレートに切り分けてheader.php、footer.php、sidebar.phpを作成 → サイドバーを作るならregister_sidebar()を作成したほうがよいかなと思いました。

サンプルのHTLMファイルにアーカイブや固定ページ用のファイルを用意しておいて、時間があったり早く進む人はアーカイブページとかを作ってもらうほうがよいかなと思うのですがどうでしょうか。

**Comment by kurudrive** [comment]
パンくずというよりは条件分岐の説明が必要だと思っているので、条件分岐を理解する上でパンくずが一番良い題材かなという考えです。

あと、固定ページ用とかは静的HTMLで用意するとまたPHPタグ全部書き換えないといけなくなるからやるならindex.phpを複製でいいかなーと思いつつ、今までの流れで条件分岐タグでほぼまかなえちゃってるから今回は無しで良いかなと...

**Comment by mignonstyle** [comment]
> 条件分岐を理解する上でパンくずが一番良い題材かなという考えです。

了解です。そういう意図でしたらパンくずは生きでよいと思いますが、実際の業務ではプラグインを使われる方が多いかと思うので、パンくずのプラグインについても参考程度に記載があるとよいかなと思いますがどうでしょう？

**Comment by mignonstyle** [comment]
> 今までの流れで条件分岐タグでほぼまかなえちゃってるから今回は無しで良いかなと...

そうですねー。今回の流れ的には条件分岐タグで十分ですが、ここは「時間があれば」なので、index.phpを複製して固定ページやアーカイブページを作成していくという流れを入れて、できればテンプレート階層についての記載を追加していただけると、ひとつステップアップできるかなと思います。

はじめての方にはテンプレート階層は難しいかもしれませんが、WordPressでは読み込まれるファイルが決まっている（静的サイトではファイル名を自由につけれるが、WordPressではルールがある）ということだけでも覚えておいてもらえたらと思うのですがいかがでしょうか？

**Comment by kurudrive** [comment]
追記しましたん

**Comment by mignonstyle** [comment]
ありがとうございますー！
