### ISSUE TITLE
もっと詳しく知りたい方は 参考サイトなどを紹介してはどうか？

### ISSUE THREAD

**Issue by mignonstyle** [wckansai2016/make-wp-theme#9]
> 興味がある人はいろいろ調べてみてください。

とあるので、参考サイトや本やスライドなどがあれば記載してあげたら親切かなと思いました。
ただ、推奨される書き方を紹介している本やサイトはあまりないので、もしあればで結構です。

**Comment by kurudrive** [comment]
とりあえずCodexは追加しましたが、公式なもの以外紹介するとどこかで何かケチがつくかもしれないので、公式なものだけの記載に留めておきたいと思います。

**Comment by mignonstyle** [comment]
了解ですー。ありがとうございますー！
